#!/bin/bash

echo "[LAUNCH] Open Targets Platform API"
docker run -d \
  -p ${OTP_API_PORT}:${OTP_API_PORT} \
  --log-driver=gcplogs \
  -e SLICK_CLICKHOUSE_URL='${SLICK_CLICKHOUSE_URL}' \
  -e ELASTICSEARCH_HOST='${ELASTICSEARCH_HOST}' \
  quay.io/opentargets/platform-api:${PLATFORM_API_VERSION}

# -e CONFIG_OT_META_APIVERSION_MAJOR=${API_VERSION_MAJOR} \
# -e CONFIG_OT_META_APIVERSION_MINOR=${API_VERSION_MINOR} \
# -e CONFIG_OT_META_APIVERSION_PATCH=${API_VERSION_PATCH} \
# -e CONFIG_OT_META_DATAVERSION_YEAR=${API_DATA_YEAR} \
# -e CONFIG_OT_META_DATAVERSION_MONTH=${API_DATA_MONTH} \
# -e CONFIG_OT_META_DATAVERSION_ITERATION=${API_DATA_ITER} \
