volumes:
  prometheus-data: {}
  grafana-data: {}
  alertmanager-data: {}

services:
  node_exporter:
    image: quay.io/prometheus/node-exporter:latest
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - /opt/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - /opt/prometheus/application_default_credentials.json:/etc/prometheus/application_default_credentials.json
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/etc/prometheus/application_default_credentials.json

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    volumes:
      - grafana-data:/var/lib/grafana
      - /opt/grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
      - /opt/grafana/dashboards:/etc/grafana/provisioning/dashboards