apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    uid: prometheusdatasource
  - name: Loki
    type: loki
    access: proxy
    url: http://gateway:3100
    isDefault: true
    editable: true
    uid: lokidatasource
