#cloud-config

users:
  - name: cloudservice
    uid: 2000

write_files:
  - path: /etc/systemd/system/nodeexporter.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start node exporter from a docker container

      [Service]
      ExecStart=/usr/bin/docker run --name=nodeexporter --rm -d --net="host" --pid="host" -v "/:/host:ro,rslave" quay.io/prometheus/node-exporter:latest --path.rootfs=/host

  - path: /etc/systemd/system/cloudservice.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start open targets platform Clickhouse docker container

      [Service]
      ExecStart=/usr/bin/docker run --rm -d --name otp-ch --log-driver=gcplogs -p 9000:9000 -p 8123:8123 -v ${CH_DATA_VOLUME}/config.d:/etc/clickhouse-server/config.d -v ${CH_DATA_VOLUME}/users.d:/etc/clickhouse-server/users.d -v ${CH_DATA_VOLUME}/data:/var/lib/clickhouse --ulimit nofile=262144:262144 ${DOCKER_IMAGE_CLICKHOUSE}

runcmd:
- systemctl daemon-reload
- systemctl start cloudservice.service
- systemctl start nodeexporter.service

bootcmd:
- fsck.ext4 -tvy ${GCP_DEVICE_DISK_PREFIX}${DATA_DISK_DEVICE_NAME_CH}
- mkdir -p ${CH_DATA_VOLUME}
- mount -t ext4 ${GCP_DEVICE_DISK_PREFIX}${DATA_DISK_DEVICE_NAME_CH} ${CH_DATA_VOLUME}
