#cloud-config

users:
  - name: cloudservice
    uid: 2000

write_files:
  - path: /etc/systemd/system/config-firewall.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Configures the host firewall

      [Service]
      Type=oneshot
      RemainAfterExit=true
      ExecStart=/sbin/iptables -A INPUT -p tcp --dport 9100 -j ACCEPT
  - path: /etc/systemd/system/nodeexporter.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start node exporter from a docker container

      [Service]
      ExecStart=/usr/bin/docker run --name=nodeexporter --rm -d --net="host" --pid="host" -v "/:/host:ro,rslave" ${DOCKER_IMAGE_NODE_EXPORTER} --path.rootfs=/host

  - path: /etc/systemd/system/cloudservice.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start open targets platform Clickhouse docker container

      [Service]
      ExecStart=/usr/bin/docker run --rm -d --name otp-ch --log-driver=gcplogs -p 9000:9000 -p 8123:8123 -p 9363:9363 -v ${CH_DATA_VOLUME}/config.d:/etc/clickhouse-server/config.d -v ${CH_DATA_VOLUME}/users.d:/etc/clickhouse-server/users.d -v ${CH_DATA_VOLUME}/data:/var/lib/clickhouse --ulimit nofile=262144:262144 ${DOCKER_IMAGE_CLICKHOUSE}

  
  - path: /etc/systemd/system/alloy.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start alloy to gather container logs and send them to the loki server

      [Service]
      ExecStart=docker run -d --name alloy --rm -p 12345:12345 -p 4317:4317 -p 4318:4318 --add-host host.docker.internal:host-gateway -v /var/run/docker.sock:/var/run/docker.sock -v /home/cloudservice/logs-config/config.alloy:/etc/alloy/config.alloy ${DOCKER_IMAGE_ALLOY} run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

runcmd:
- |
  cd /home/cloudservice
  mkdir -p logs-config
  wget --header='Metadata-Flavor: Google' 'http://metadata.google.internal/computeMetadata/v1/instance/attributes/config-alloy'
  mv config-alloy logs-config/config.alloy
- |
  systemctl daemon-reload
  systemctl start config-firewall.service
  systemctl start cloudservice.service
  systemctl start nodeexporter.service
  systemctl start alloy.service

bootcmd:
- fsck.ext4 -tvy ${GCP_DEVICE_DISK_PREFIX}${DATA_DISK_DEVICE_NAME_CH}
- mkdir -p ${CH_DATA_VOLUME}
- mount -t ext4 ${GCP_DEVICE_DISK_PREFIX}${DATA_DISK_DEVICE_NAME_CH} ${CH_DATA_VOLUME}
