services:
  clickhouse:
    image: ${DOCKER_IMAGE_CLICKHOUSE}
    container_name: $${otp-ch}
    logging:
      driver: gcplogs
    ports:
      - "9000:9000"
      - "8123:8123"
      - "9363:9363"
    volumes:
      - ${CH_DATA_VOLUME}/config.d:/etc/clickhouse-server/config.d
      - ${CH_DATA_VOLUME}/users.d:/etc/clickhouse-server/users.d
      - ${CH_DATA_VOLUME}/data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  node_exporter:
    image: ${DOCKER_IMAGE_NODE_EXPORTER}
    container_name: node_exporter
    command:
      - '--path.rootfs=/host'
    network_mode: host
    pid: host
    restart: unless-stopped
    volumes:
      - '/:/host:ro,rslave'