#cloud-config

users:
  - name: cloudservice
    uid: 2000

write_files:
  - path: /etc/systemd/system/config-firewall.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Configures the host firewall

      [Service]
      Type=oneshot
      RemainAfterExit=true
      ExecStart=/sbin/iptables -A INPUT -p tcp --dport 9100 -j ACCEPT
  - path: /etc/systemd/system/nodeexporter.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start node exporter from a docker container

      [Service]
      ExecStart=/usr/bin/docker run --name=nodeexporter --rm -d --net="host" --pid="host" -v "/:/host:ro,rslave" ${node_exporter_image} --path.rootfs=/host

  - path: /etc/systemd/system/webapp.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start open targets platform Web App docker container

      [Service]
      ExecStart=/usr/bin/docker run --name=ot_webapp -d --log-driver=gcplogs -p 8080:8080 ${env_vars} ghcr.io/opentargets/ot-ui-apps:${webapp_image_version}

  - path: /etc/systemd/system/alloy.service
    permissions: 0644
    owner: root
    content: |
      [Unit]
      Description=Start alloy to gather container logs and send them to the loki server

      [Service]
      ExecStart=docker run -d --name alloy --rm -p 12345:12345 -p 4317:4317 -p 4318:4318 --add-host host.docker.internal:host-gateway -v /var/run/docker.sock:/var/run/docker.sock -v /home/cloudservice/logs-config/config.alloy:/etc/alloy/config.alloy ${alloy_image} run --server.http.listen-addr=0.0.0.0:12345 --storage.path=/var/lib/alloy/data /etc/alloy/config.alloy

runcmd:
- |
  cd /home/cloudservice
  mkdir -p logs-config
  wget --header='Metadata-Flavor: Google' 'http://metadata.google.internal/computeMetadata/v1/instance/attributes/config-alloy'
  mv config-alloy logs-config/config.alloy
- |
  systemctl daemon-reload
  systemctl start config-firewall.service
  systemctl start webapp.service
  systemctl start nodeexporter.service
  systemctl start alloy.service