{
 "title": "OT Dash",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "New panel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  { "title": "Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "DB requests rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum by (database)(rate(platform_api_db_query_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GraphQL Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "sum by(nodename)(rate(platform_api_graphql_requests_total[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "QuickView Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Usage Webapp",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{nodename=~\"^.*-web-[0-9]*-.*\"} - node_memory_MemAvailable_bytes{nodename=~\"^.*-web-[0-9]*-.*\"})/node_memory_MemTotal_bytes{nodename=~\"^.*-web-[0-9]*-.*\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory Usage Api",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{nodename=~\"^.*-api-[0-9]*-.*\"} - node_memory_MemAvailable_bytes{nodename=~\"^.*-api-[0-9]*-.*\"})/node_memory_MemTotal_bytes{nodename=~\"^.*-api-[0-9]*-.*\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory Usage AI Api",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{nodename=~\"^.*-ai-[0-9]*-.*\"} - node_memory_MemAvailable_bytes{nodename=~\"^.*-ai-[0-9]*-.*\"})/node_memory_MemTotal_bytes{nodename=~\"^.*-ai-[0-9]*-.*\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory Usage Clickhouse",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{nodename=~\"^.*-es-[0-9]*-.*\"} - node_memory_MemAvailable_bytes{nodename=~\"^.*-es-[0-9]*-.*\"})/node_memory_MemTotal_bytes{nodename=~\"^.*-es-[0-9]*-.*\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory Usage Opensearch",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{nodename=~\"^.*-es-[0-9]*-.*\"} - node_memory_MemAvailable_bytes{nodename=~\"^.*-es-[0-9]*-.*\"})/node_memory_MemTotal_bytes{nodename=~\"^.*-es-[0-9]*-.*\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory Usage Prometheus",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{nodename=~\"^.*-pro-[0-9]*-.*\"} - node_memory_MemAvailable_bytes{nodename=~\"^.*-pro-[0-9]*-.*\"})/node_memory_MemTotal_bytes{nodename=~\"^.*-pro-[0-9]*-.*\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "QuickView CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage webserver",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\", nodename=~\"^.*-web-[0-9]*-.*\"}[1m])))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Usage Api",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\", nodename=~\"^.*-api-[0-9]*-.*\"}[1m])))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Usage AI Api",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\", nodename=~\"^.*-ai-[0-9]*-.*\"}[1m])))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Usage Clickhouse",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\", nodename=~\"^.*-ch-[0-9]*-.*\"}[1m])))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Usage Opensearch",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 8, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\", nodename=~\"^.*-es-[0-9]*-.*\"}[1m])))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "CPU Usage Prometheus",
     "type": "gauge",
     "gridPos": { "h": 5, "w": 8, "x": 16, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\", nodename=~\"^.*-pro-[0-9]*-.*\"}[1m])))",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage Per instance",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1 - avg by(nodename) (rate(node_cpu_seconds_total{mode=\"idle\", nodename!=\"\"}[$__rate_interval])))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(node_memory_MemTotal_bytes{nodename!=\"\"} - node_memory_MemAvailable_bytes{nodename!=\"\"})/node_memory_MemTotal_bytes{nodename!=\"\"}",
       "legendFormat": "{{nodename}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network Incoming Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "pps" } },
     "targets": [
      {
       "expr": "sum by (nodename)(rate(node_network_receive_packets_total{job=\"node\"}[$__rate_interval]))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Network Outgoing Packets",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "targets": [
      {
       "expr": "sum by (nodename)(rate(node_network_transmit_packets_total{job=\"node\"}[$__rate_interval]))",
       "legendFormat": "{{nodename}}"
      }
     ]
    },
    {
     "title": "Network Traffic Drop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "sum by (nodename) (rate(node_network_receive_drop_total{job=\"node\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}